import type { Metadata } from "next";
import { roboto } from "@/src/config/font";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

