import type { Metadata } from "next";
import { roboto } from "@/src/config/font";
import "../globals.css";



export const metadata: Metadata = {
  title: "CChang Constructora",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}
